//! HTML payment link support for browser-based payments.
//!
//! When `html` is enabled on the server config, 402 responses can be rendered
//! as interactive HTML payment pages instead of JSON. The page embeds a bundled
//! Solana payment UI that handles wallet connection, transaction signing, and
//! credential submission via a service worker.
//!
//! # Usage
//!
//! ```ignore
//! use solana_mpp::server::html;
//!
//! // In your HTTP handler:
//! if html::accepts_html(accept_header) && mpp.html_enabled() {
//!     if html::is_service_worker_request(query_string) {
//!         // Serve the service worker JS
//!         return respond_js(html::service_worker_js());
//!     }
//!     let challenge = mpp.charge("1.00")?;
//!     let page = html::challenge_to_html(&challenge, mpp.rpc_url(), mpp.network());
//!     return respond_html(page);
//! }
//! ```

use crate::protocol::core::PaymentChallenge;

/// Bundled payment UI JavaScript (auto-generated by `html/build.ts`).
const PAYMENT_UI_JS: &str = include_str!("html/payment_ui.gen.js");

/// Bundled service worker JavaScript (auto-generated by `html/build.ts`).
const SERVICE_WORKER_JS: &str = include_str!("html/service_worker.gen.js");

/// Query parameter that triggers serving the service worker JS file.
pub const SERVICE_WORKER_PARAM: &str = "__mpp_worker";

/// ID of the embedded data `<script>` element.
const DATA_ELEMENT_ID: &str = "__MPP_DATA__";

/// Check if an HTTP `Accept` header value includes `text/html`.
pub fn accepts_html(accept: &str) -> bool {
    accept
        .split(',')
        .any(|part| part.trim().starts_with("text/html"))
}

/// Check if a URL query string contains the service worker parameter.
pub fn is_service_worker_request(query: &str) -> bool {
    query.contains(SERVICE_WORKER_PARAM)
}

/// Returns the service worker JavaScript content.
///
/// Serve this with `Content-Type: application/javascript` when
/// `is_service_worker_request()` returns true.
pub fn service_worker_js() -> &'static str {
    SERVICE_WORKER_JS
}

/// Render a payment challenge as a self-contained HTML payment page.
///
/// The returned HTML includes:
/// - A `<pre>` block showing the challenge details
/// - An embedded JSON data block with the challenge for the payment UI
/// - The bundled payment UI script (inlined)
/// - A CSP meta tag restricting script sources
///
/// All user-controlled values are HTML-escaped to prevent XSS.
pub fn challenge_to_html(
    challenge: &PaymentChallenge,
    rpc_url: &str,
    network: &str,
) -> String {
    let challenge_json = serde_json::to_string_pretty(challenge).unwrap_or_default();
    let test_mode = matches!(network, "devnet" | "localnet");

    // Build the embedded data object for the payment UI
    let embedded_data = serde_json::json!({
        "challenge": challenge,
        "network": network,
        "rpcUrl": rpc_url,
        "testMode": test_mode,
    });
    let embedded_json = serde_json::to_string(&embedded_data).unwrap_or_default();

    let description_line = challenge
        .description
        .as_deref()
        .map(|d| format!("<p style=\"color:#4a5568;text-align:center\">{}</p>", escape_html(d)))
        .unwrap_or_default();

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Payment Required</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 20px; background: #f7fafc; color: #1a202c; }}
pre {{ background: #edf2f7; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px; max-width: 600px; margin: 20px auto; }}
</style>
</head>
<body>
{description}
<details style="max-width:600px;margin:0 auto 20px">
<summary style="cursor:pointer;color:#718096;font-size:14px">Challenge details</summary>
<pre>{challenge_json}</pre>
</details>
<div id="root"></div>
<script type="application/json" id="{data_id}">{embedded_json}</script>
<script>{payment_ui_js}</script>
</body>
</html>"#,
        description = description_line,
        challenge_json = escape_html(&challenge_json),
        data_id = DATA_ELEMENT_ID,
        embedded_json = embedded_json, // JSON is safe inside type="application/json"
        payment_ui_js = PAYMENT_UI_JS,
    )
}

/// HTML-escape a string to prevent XSS when interpolating into HTML content.
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::core::{Base64UrlJson, types::{MethodName, IntentName}};

    fn test_challenge(description: Option<&str>) -> PaymentChallenge {
        PaymentChallenge {
            id: "test-challenge-id".to_string(),
            realm: "test.example.com".to_string(),
            method: MethodName::new("solana"),
            intent: IntentName::new("charge"),
            request: Base64UrlJson::from_typed(
                &serde_json::json!({"amount": "1000000", "currency": "USDC", "recipient": "CXhrFZJLKqjzmP3sjYLcF4dTeXWKCy9e2SXXZ2Yo6MPY"}),
            ).unwrap(),
            expires: Some("2099-01-01T00:00:00Z".to_string()),
            description: description.map(|s| s.to_string()),
            digest: None,
            opaque: None,
        }
    }

    #[test]
    fn test_accepts_html() {
        assert!(accepts_html("text/html,application/xhtml+xml,*/*"));
        assert!(accepts_html("text/html"));
        assert!(!accepts_html("application/json"));
        assert!(!accepts_html("*/*")); // Don't match wildcard — be explicit
    }

    #[test]
    fn test_is_service_worker_request() {
        assert!(is_service_worker_request("__mpp_worker=1"));
        assert!(is_service_worker_request("foo=bar&__mpp_worker=1"));
        assert!(!is_service_worker_request("foo=bar"));
        assert!(!is_service_worker_request(""));
    }

    #[test]
    fn test_escape_html() {
        assert_eq!(
            escape_html("<script>alert('xss')</script>"),
            "&lt;script&gt;alert(&#x27;xss&#x27;)&lt;/script&gt;"
        );
    }

    #[test]
    fn test_service_worker_js_not_empty() {
        assert!(!service_worker_js().is_empty());
    }

    #[test]
    fn test_challenge_to_html_structure() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "https://api.devnet.solana.com", "devnet");

        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("id=\"root\""));
        assert!(html.contains("id=\"__MPP_DATA__\""));
        assert!(html.contains("test-challenge-id"));
        // Payment UI script should be inlined
        assert!(html.len() > 1000);
        // Test mode should be detected for devnet
        assert!(html.contains("\"testMode\":true"));
    }

    #[test]
    fn test_challenge_to_html_mainnet_not_test_mode() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "https://api.mainnet-beta.solana.com", "mainnet-beta");
        assert!(html.contains("\"testMode\":false"));
    }

    #[test]
    fn test_challenge_to_html_xss_in_description() {
        let challenge = test_challenge(Some("<script>alert('xss')</script>"));
        let html = challenge_to_html(&challenge, "http://localhost:8899", "localnet");
        // The <script> in description must be escaped in the <p> tag
        assert!(html.contains("&lt;script&gt;alert("));
        // Raw script tag should NOT appear in description context
        assert!(!html.contains("<p style=\"color:#4a5568;text-align:center\"><script>"));
    }

    #[test]
    fn test_challenge_to_html_basic_structure() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "http://localhost:8899", "devnet");
        // CSP is set as a response header by the server, not in the HTML meta tag.
        // Verify the HTML has the essential structural elements.
        assert!(html.contains("<div id=\"root\">"));
        assert!(html.contains("<script>"));
    }

    #[test]
    fn test_html_enabled_on_mpp() {
        let mpp = crate::server::Mpp::new(crate::server::Config {
            recipient: "CXhrFZJLKqjzmP3sjYLcF4dTeXWKCy9e2SXXZ2Yo6MPY".to_string(),
            secret_key: Some("test-secret-key-long-enough-for-hmac-sha256-operations-1234567890".to_string()),
            network: "devnet".to_string(),
            html: true,
            ..Default::default()
        }).unwrap();

        assert!(mpp.html_enabled());
        assert_eq!(mpp.network(), "devnet");
        assert!(!mpp.rpc_url().is_empty());

        // Generate a challenge and render as HTML
        let challenge = mpp.charge("0.10").unwrap();
        let html = challenge_to_html(&challenge, mpp.rpc_url(), mpp.network());
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains(&challenge.id));
    }
}
